### Création d'un utilisateur
POST http://localhost:3000/signup
Content-Type: application/json

{
    "username": "user2",
    "email": "test2@test.com",
    "password": "password",
    "confirmPassword": "password",
    "avatar": "https://img.freepik.com/premium-vector/young-smiling-man-avatar-man-with-brown-beard-mustache-hair-wearing-yellow-sweater-sweatshirt-3d-vector-people-character-illustration-cartoon-minimal-style_365941-860.jpg",
    "role_id": 1
}

### Connexion d'un utilisateur
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "test2@test.com",
    "password": "password"
}

### Test Token
GET  http://localhost:3000/test
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJyb2xlIjoiZGV2ZWxvcGVyIiwiaWF0IjoxNjkzMjEzMjE3LCJleHAiOjE2OTMyMTY4MTd9.OKK4sLllNHrspu8zk-G8OWpwWhc7-WFcqwYoOyPhNNY

### Création d'un Jeux
POST http://localhost:3000/games/game
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJyb2xlIjoiZGV2ZWxvcGVyIiwiaWF0IjoxNjkzMjEzMjE3LCJleHAiOjE2OTMyMTY4MTd9.OKK4sLllNHrspu8zk-G8OWpwWhc7-WFcqwYoOyPhNNY

{
    "name": "Jeux 2",
    "description": "test",
    "picture": "https://www.jeuxvideo.com/smileys_img/45.gif",
    "external_link": "https://www.test",
    "user_id": 12,
    "release_date": "2021-05-20",
    "categories": ["screen", "porcupine", "attitude"],
    "tags": ["view", "analyst", "action"]
}

### Trouver tous les Jeux
GET http://localhost:3000/games

### Trouver un Jeux
GET http://localhost:3000/games/game/1

### Create Issue
POST http://localhost:3000/games/game/1/issues
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJyb2xlIjoiZGV2ZWxvcGVyIiwiaWF0IjoxNjkzMjEzMjE3LCJleHAiOjE2OTMyMTY4MTd9.OKK4sLllNHrspu8zk-G8OWpwWhc7-WFcqwYoOyPhNNY

{
    "title": "test7",
    "description": "test test",
    "is_minor": true,
    "is_public": true,
    "is_online": true,
    "frequency": "test",
    "replication": "test test",
    "published_at": "2021-02-13",
    "user_id": 11,
    "platform_id": 2
}

### Delete Issue
DELETE http://localhost:3000/games/game/1/issue/11
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJyb2xlIjoiZGV2ZWxvcGVyIiwiaWF0IjoxNjkzMjEzMjE3LCJleHAiOjE2OTMyMTY4MTd9.OKK4sLllNHrspu8zk-G8OWpwWhc7-WFcqwYoOyPhNNY

### Update Issue Player
PATCH http://localhost:3000/games/game/1/issue/11
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJyb2xlIjoiZGV2ZWxvcGVyIiwiaWF0IjoxNjkzMjEzMjE3LCJleHAiOjE2OTMyMTY4MTd9.OKK4sLllNHrspu8zk-G8OWpwWhc7-WFcqwYoOyPhNNY

{
    "title": "test32",
    "description": "test test test"
}

### Update Issue Developer
PATCH http://localhost:3000/games/game/13/issue/13
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJyb2xlIjoiZGV2ZWxvcGVyIiwiaWF0IjoxNjkzMjEzMjE3LCJleHAiOjE2OTMyMTY4MTd9.OKK4sLllNHrspu8zk-G8OWpwWhc7-WFcqwYoOyPhNNY

{
    "status": "accepted",
    "assign_to": "test@developer.com"
} 

### Trouver tous les Issues d'un Jeux
GET http://localhost:3000/games/game/1/issues

### Trouver un Issue d'un Jeux
GET http://localhost:3000/games/game/1/issue/1

### Create Suggestion
POST http://localhost:3000/games/game/1/suggestions
Content-Type: application/json

{
    "title": "test",
    "description": "test test",
    "is_minor": true,
    "is_public": true,
    "is_online": true,
    "frequency": "test",
    "replication": "test test",
    "published_at": "2021-02-13",
    "user_id": 1,
    "platform_id": 2
}

### Delete Suggestion
DELETE http://localhost:3000/games/game/1/suggestion/14
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJyb2xlIjoiZGV2ZWxvcGVyIiwiaWF0IjoxNjkzMjI1NjAxLCJleHAiOjE2OTMyMjkyMDF9.YSJl96mZS5lnV64JjkH8SPVz9SqJGFk6OiE52fVL9z8

### Trouver tous les Suggestions d'un Jeux
GET http://localhost:3000/games/game/1/suggestions

### Trouver un Suggestion d'un Jeux
GET http://localhost:3000/games/game/1/suggestion/1

### Trouver tous les Suggestions d'un Jeux
GET http://localhost:3000/categories
