### Création d'un utilisateur
POST http://localhost:3000/signup
Content-Type: application/json

{
    "username": "user3",
    "email": "test3@test.com",
    "password": "password",
    "confirmPassword": "password",
    "avatar": "https://img.freepik.com/premium-vector/young-smiling-man-avatar-man-with-brown-beard-mustache-hair-wearing-yellow-sweater-sweatshirt-3d-vector-people-character-illustration-cartoon-minimal-style_365941-860.jpg",
    "role_id": 1
}

### Connexion d'un utilisateur
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "test3@test.com",
    "password": "password"
}

### Test Token
GET  http://localhost:3000/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJyb2xlIjoiZGV2ZWxvcGVyIiwidXNlcm5hbWUiOiJ1c2VyMyIsImlhdCI6MTY5MzgzMTQ1MSwiZXhwIjoxNjkzODM1MDUxfQ.nnM6QImvhwGQrHb45gBubFn6ed2ukrMPOeLqU3Cuc7A

### Création d'un Jeux
POST http://localhost:3000/games/game
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJyb2xlIjoiZGV2ZWxvcGVyIiwidXNlcm5hbWUiOiJ1c2VyMyIsImlhdCI6MTY5MzgzMTQ1MSwiZXhwIjoxNjkzODM1MDUxfQ.nnM6QImvhwGQrHb45gBubFn6ed2ukrMPOeLqU3Cuc7A

{
    "name": "Jeux test2",
    "description": "test",
    "picture": "https://www.jeuxvideo.com/smileys_img/45.gif",
    "external_link": "https://www.test",
    "release_date": "2021-05-20",
    "categories": ["Action", "Adventure", "Casual"],
    "tags": ["view", "analyst", "action"]
}

### Update d'un Jeux
PATCH http://localhost:3000/games/game/16
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJyb2xlIjoiZGV2ZWxvcGVyIiwidXNlcm5hbWUiOiJ1c2VyMyIsImlhdCI6MTY5MzgzMTQ1MSwiZXhwIjoxNjkzODM1MDUxfQ.nnM6QImvhwGQrHb45gBubFn6ed2ukrMPOeLqU3Cuc7A

{
    "name": "Jeux 5465",
    "description": "test2"
}

### Delete d'un Jeux
DELETE http://localhost:3000/games/game/16
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJyb2xlIjoiZGV2ZWxvcGVyIiwidXNlcm5hbWUiOiJ1c2VyMyIsImlhdCI6MTY5MzgzMTQ1MSwiZXhwIjoxNjkzODM1MDUxfQ.nnM6QImvhwGQrHb45gBubFn6ed2ukrMPOeLqU3Cuc7A

### Trouver tous les Jeux
GET http://localhost:3000/games

### Trouver un Jeux
GET http://localhost:3000/games/game/16

### Create Issue
POST http://localhost:3000/games/game/1/issues
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJyb2xlIjoiZGV2ZWxvcGVyIiwidXNlcm5hbWUiOiJ1c2VyMyIsImlhdCI6MTY5MzgzMTQ1MSwiZXhwIjoxNjkzODM1MDUxfQ.nnM6QImvhwGQrHb45gBubFn6ed2ukrMPOeLqU3Cuc7A

{
    "title": "test32g",
    "description": "test test",
    "is_minor": true,
    "is_public": true,
    "is_online": true,
    "frequency": "test",
    "replication": "test test",
    "published_at": "2021-02-13",
    "user_id": 11,
    "platform_id": 2,
    "tags": ["view", "analyst", "action"]
}

### Delete Issue
DELETE http://localhost:3000/issue/12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJyb2xlIjoiZGV2ZWxvcGVyIiwidXNlcm5hbWUiOiJ1c2VyMyIsImlhdCI6MTY5MzgzMTQ1MSwiZXhwIjoxNjkzODM1MDUxfQ.nnM6QImvhwGQrHb45gBubFn6ed2ukrMPOeLqU3Cuc7A

### Update Issue Player
PATCH http://localhost:3000/issue/12
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJyb2xlIjoiZGV2ZWxvcGVyIiwidXNlcm5hbWUiOiJ1c2VyMyIsImlhdCI6MTY5MzgzMTQ1MSwiZXhwIjoxNjkzODM1MDUxfQ.nnM6QImvhwGQrHb45gBubFn6ed2ukrMPOeLqU3Cuc7A

{
    "title": "test1",
    "description": "test test test"
}

### Update Issue Developer
PATCH http://localhost:3000/issue/12
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJyb2xlIjoiZGV2ZWxvcGVyIiwidXNlcm5hbWUiOiJ1c2VyMyIsImlhdCI6MTY5MzgzMTQ1MSwiZXhwIjoxNjkzODM1MDUxfQ.nnM6QImvhwGQrHb45gBubFn6ed2ukrMPOeLqU3Cuc7A

{
    "status": "accepted",
    "assign_to": "test@developer.com"
} 

### Trouver tous les Issues d'un Jeux
GET http://localhost:3000/games/game/1/issues

### Trouver un Issue d'un Jeux
GET http://localhost:3000/issue/12

### Create Suggestion
POST http://localhost:3000/games/game/1/suggestions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJyb2xlIjoicGxheWVyIiwidXNlcm5hbWUiOiJ1c2VyIiwiaWF0IjoxNjkzMzE1MzI1LCJleHAiOjE2OTMzMTg5MjV9.Q5C6ZiNFWBK_0Dv8IBfP86W_eV1DQzcp0F5hPsp7QWc

{
    "title": "test",
    "description": "test test",
    "is_minor": true,
    "is_public": true,
    "is_online": true,
    "frequency": "test",
    "replication": "test test",
    "published_at": "2021-02-13",
    "user_id": 11,
    "platform_id": 2
}

### Delete Suggestion
DELETE http://localhost:3000/suggestion/13
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJyb2xlIjoicGxheWVyIiwidXNlcm5hbWUiOiJ1c2VyIiwiaWF0IjoxNjkzMjkxNjc2LCJleHAiOjE2OTMyOTUyNzZ9.VXBl1lFRL7DXRj19fun0IVSdzH7l5QvYd0WU-7nWITQ

### Update Suggestion 
PATCH http://localhost:3000/suggestion/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJyb2xlIjoiZGV2ZWxvcGVyIiwiaWF0IjoxNjkzMjEzMjE3LCJleHAiOjE2OTMyMTY4MTd9.OKK4sLllNHrspu8zk-G8OWpwWhc7-WFcqwYoOyPhNNY

{
    "title": "Patch test successful",
    "description": "test test of patch test"
} 

### Trouver tous les Suggestions d'un Jeux
GET http://localhost:3000/games/game/1/suggestions

### Trouver un Suggestion 
GET http://localhost:3000/suggestion/1

### Trouver tous les Catégories
GET http://localhost:3000/categories

### Trouver tous les users
GET http://localhost:3000/users

### Trouver un user
GET http://localhost:3000/users/11

### Update un user
PATCH http://localhost:3000/users/11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJyb2xlIjoiZGV2ZWxvcGVyIiwidXNlcm5hbWUiOiJ1c2VyMyIsImlhdCI6MTY5MzgzMTQ1MSwiZXhwIjoxNjkzODM1MDUxfQ.nnM6QImvhwGQrHb45gBubFn6ed2ukrMPOeLqU3Cuc7A

{
    "username": "user3",
    "old_password": "password",
    "new_password": "password9",
    "confirm_password": "password9"
}

### Search exact
GET http://localhost:3000/search?search=Thoughtful-lemon

### Search partial
GET http://localhost:3000/search?search=Thoughtful

### Search vague
GET http://localhost:3000/search?search=a

### Trouver toutes les plateformes
GET http://localhost:3000/platforms

### Trouver les tags à partir d'un jeu
GET http://localhost:3000/games/game/1/tags

### Trouver les tags
GET http://localhost:3000/tags
